#version 300 es
// psBumpedMirror (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psBumpedMirror.psh
// Shadow comparisons subtract nearby projected depths; mediump loses the
// difference, especially at distant camera positions. GLES 3 supports highp.
precision highp float;
uniform vec4 pc[8];
// D3DRS_ALPHATESTENABLE / ALPHAFUNC / ALPHAREF are device state in D3D, so
// they are uniforms here rather than baked per shader (the engine changes the
// reference at run time through SetAlphaRef).  alphaFunc uses D3DCMP values,
// 0 = disabled.
uniform int alphaFunc;
uniform float alphaRef;
#ifdef A5_CUBE0
uniform highp samplerCube s0;
#define TEX0(c)  texture(s0, (c).xyz)
#define TEXP0(c) texture(s0, (c).xyz)
#else
uniform highp sampler2D s0;
#define TEX0(c)  texture(s0, (c).xy)
#define TEXP0(c) textureProj(s0, (c).xyw)
#endif
#ifdef A5_CUBE3
uniform highp samplerCube s3;
#define TEX3(c)  texture(s3, (c).xyz)
#define TEXP3(c) texture(s3, (c).xyz)
#else
uniform highp sampler2D s3;
#define TEX3(c)  texture(s3, (c).xy)
#define TEXP3(c) textureProj(s3, (c).xyw)
#endif
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
bool a5AlphaTestFails(float a)
{
    switch (alphaFunc) {
        case 1: return true;                 // D3DCMP_NEVER
        case 2: return !(a <  alphaRef);     // LESS
        case 3: return !(a == alphaRef);     // EQUAL
        case 4: return !(a <= alphaRef);     // LESSEQUAL
        case 5: return !(a >  alphaRef);     // GREATER
        case 6: return !(a != alphaRef);     // NOTEQUAL
        case 7: return !(a >= alphaRef);     // GREATEREQUAL
        default: return false;               // 0 disabled, 8 ALWAYS
    }
}
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = TEX0(vT0);
    float m3x3_1 = dot(vT1.xyz, ((t0 * 2.0 - 1.0)).xyz);
    float m3x3_2 = dot(vT2.xyz, ((t0 * 2.0 - 1.0)).xyz);
    float m3x3_3 = dot(vT3.xyz, ((t0 * 2.0 - 1.0)).xyz);
    vec3 m3x3_N = vec3(m3x3_1, m3x3_2, m3x3_3);
    vec3 m3x3_E = vec3(vT1.w, vT2.w, vT3.w);
    vec3 m3x3_R = 2.0 * dot(m3x3_N, m3x3_E) * m3x3_N - dot(m3x3_N, m3x3_N) * m3x3_E;
    vec4 t3 = TEX3(vec4(m3x3_R, 1.0));
    r0 = clamp(t3, -1.0, 1.0);
    vec4 a5Out = clamp(r0, 0.0, 1.0);
    if (a5AlphaTestFails(a5Out.a)) discard;
    fragColor = a5Out;
}
