#version 300 es
// psFastFullBump4 (ps.1.4) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psFastFullBump4.psh
// Shadow comparisons subtract nearby projected depths; mediump loses the
// difference, especially at distant camera positions. GLES 3 supports highp.
precision highp float;
uniform vec4 pc[8];
// D3DRS_ALPHATESTENABLE / ALPHAFUNC / ALPHAREF are device state in D3D, so
// they are uniforms here rather than baked per shader (the engine changes the
// reference at run time through SetAlphaRef).  alphaFunc uses D3DCMP values,
// 0 = disabled.
uniform int alphaFunc;
uniform float alphaRef;
#ifdef A5_CUBE0
uniform highp samplerCube s0;
#define TEX0(c)  texture(s0, (c).xyz)
#define TEXP0(c) texture(s0, (c).xyz)
#else
uniform highp sampler2D s0;
#define TEX0(c)  texture(s0, (c).xy)
#define TEXP0(c) textureProj(s0, (c).xyw)
#endif
#ifdef A5_CUBE1
uniform highp samplerCube s1;
#define TEX1(c)  texture(s1, (c).xyz)
#define TEXP1(c) texture(s1, (c).xyz)
#else
uniform highp sampler2D s1;
#define TEX1(c)  texture(s1, (c).xy)
#define TEXP1(c) textureProj(s1, (c).xyw)
#endif
#ifdef A5_CUBE2
uniform highp samplerCube s2;
#define TEX2(c)  texture(s2, (c).xyz)
#define TEXP2(c) texture(s2, (c).xyz)
#else
uniform highp sampler2D s2;
#define TEX2(c)  texture(s2, (c).xy)
#define TEXP2(c) textureProj(s2, (c).xyw)
#endif
#ifdef A5_CUBE3
uniform highp samplerCube s3;
#define TEX3(c)  texture(s3, (c).xyz)
#define TEXP3(c) texture(s3, (c).xyz)
#else
uniform highp sampler2D s3;
#define TEX3(c)  texture(s3, (c).xy)
#define TEXP3(c) textureProj(s3, (c).xyw)
#endif
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
bool a5AlphaTestFails(float a)
{
    switch (alphaFunc) {
        case 1: return true;                 // D3DCMP_NEVER
        case 2: return !(a <  alphaRef);     // LESS
        case 3: return !(a == alphaRef);     // EQUAL
        case 4: return !(a <= alphaRef);     // LESSEQUAL
        case 5: return !(a >  alphaRef);     // GREATER
        case 6: return !(a != alphaRef);     // NOTEQUAL
        case 7: return !(a >= alphaRef);     // GREATEREQUAL
        default: return false;               // 0 disabled, 8 ALWAYS
    }
}
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 r1 = vec4(0.0);
    vec4 r2 = vec4(0.0);
    vec4 r3 = vec4(0.0);
    vec4 r4 = vec4(0.0);
    vec4 r5 = vec4(0.0);
    r0 = TEX0(vT0);
    r1 = TEX1(vT1);
    r2 = TEXP2(vT2);
    r3 = TEXP3(vT3);
    r4 = clamp(vec4(dot(((r0 * 2.0 - 1.0)).xyz, ((vD0 * 2.0 - 1.0)).xyz)), 0.0, 1.0);
    vec4 co_a5 = clamp(vec4(dot(((r0 * 2.0 - 1.0)).xyz, ((vD1 * 2.0 - 1.0)).xyz)), -1.0, 1.0);
    vec4 co_b5 = clamp((r4.wwww * vD1.wwww), -1.0, 1.0);
    r5.xyz = (co_a5).xyz;
    r4.w = (co_b5).w;
    r5.xyz = (clamp((r5 * pc[2] + pc[1]), -1.0, 1.0)).xyz;
    r5.xyz = (clamp((r5 * r2.wwww + r2), -1.0, 1.0)).xyz;
    r5.xyz = (clamp((r5 * r1), -1.0, 1.0)).xyz;
    r4.xyz = (clamp((r4.wwww * pc[3]), -1.0, 1.0)).xyz;
    vec4 co_a11 = clamp((r4 * r3), -1.0, 1.0);
    vec4 co_b11 = clamp(r2.wwww, -1.0, 1.0);
    r4.xyz = (co_a11).xyz;
    r0.w = (co_b11).w;
    r0.xyz = (clamp(((r4 * r1 + r5) * 4.0), -1.0, 1.0)).xyz;
    vec4 a5Out = clamp(r0, 0.0, 1.0);
    if (a5AlphaTestFails(a5Out.a)) discard;
    fragColor = a5Out;
}
