#version 300 es
// psTexturedFog (ps.1.1) -- generated by tools/d3dasm2glsl.py from shaders/d3d/ps/psTexturedFog.psh
// Shadow comparisons subtract nearby projected depths; mediump loses the
// difference, especially at distant camera positions. GLES 3 supports highp.
precision highp float;
uniform vec4 pc[8];
// D3DRS_ALPHATESTENABLE / ALPHAFUNC / ALPHAREF are device state in D3D, so
// they are uniforms here rather than baked per shader (the engine changes the
// reference at run time through SetAlphaRef).  alphaFunc uses D3DCMP values,
// 0 = disabled.
uniform int alphaFunc;
uniform float alphaRef;
#ifdef A5_CUBE0
uniform highp samplerCube s0;
#define TEX0(c)  texture(s0, (c).xyz)
#define TEXP0(c) texture(s0, (c).xyz)
#else
uniform highp sampler2D s0;
#define TEX0(c)  texture(s0, (c).xy)
#define TEXP0(c) textureProj(s0, (c).xyw)
#endif
#ifdef A5_CUBE2
uniform highp samplerCube s2;
#define TEX2(c)  texture(s2, (c).xyz)
#define TEXP2(c) texture(s2, (c).xyz)
#else
uniform highp sampler2D s2;
#define TEX2(c)  texture(s2, (c).xy)
#define TEXP2(c) textureProj(s2, (c).xyw)
#endif
in vec4 vD0;
in vec4 vD1;
in vec4 vT0;
in vec4 vT1;
in vec4 vT2;
in vec4 vT3;
out vec4 fragColor;
bool a5AlphaTestFails(float a)
{
    switch (alphaFunc) {
        case 1: return true;                 // D3DCMP_NEVER
        case 2: return !(a <  alphaRef);     // LESS
        case 3: return !(a == alphaRef);     // EQUAL
        case 4: return !(a <= alphaRef);     // LESSEQUAL
        case 5: return !(a >  alphaRef);     // GREATER
        case 6: return !(a != alphaRef);     // NOTEQUAL
        case 7: return !(a >= alphaRef);     // GREATEREQUAL
        default: return false;               // 0 disabled, 8 ALWAYS
    }
}
void main()
{
    vec4 r0 = vec4(0.0);
    vec4 t0 = TEX0(vT0);
    float m3x2_u = dot(vT1.xyz, (t0).xyz);
    float m3x2_v = dot(vT2.xyz, (t0).xyz);
    vec4 t2 = TEX2(vec4(m3x2_u, m3x2_v, 0.0, 1.0));
    r0 = clamp(t2, -1.0, 1.0);
    vec4 a5Out = clamp(r0, 0.0, 1.0);
    if (a5AlphaTestFails(a5Out.a)) discard;
    fragColor = a5Out;
}
