//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MapEdit.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_TEDIT                       102
#define IDD_LIGHT_PREFS                 102
#define ID_ADDPLACEMENT                 103
#define ID_DELRECT                      104
#define ID_DELPLACEMENT                 105
#define ID_ADDTEMPLATE                  106
#define IDD_EXPORT_PREFS                106
#define ID_DELTEMPLATE                  107
#define IDD_PROPPAGE_PERSITEMS          107
#define ID_OI                           108
#define ID_ACTIVE_WALL                  113
#define ID_IMPORTITEM                   114
#define ID_NEWCONTOUR                   115
#define ID_DELCONTOUR                   116
#define ID_HOLEPROPS                    117
#define ID_ADDUNIT                      118
#define ID_ADDCONTAINER                 119
#define ID_ADDMODEL                     120
#define ID_ADDLIGHT                     121
#define ID_ADDEXPLOSION                 122
#define ID_NEW_TEXSPOT                  123
#define ID_ADDTERRSPOT                  124
#define ID_ADDWAYPOINT                  125
#define ID_ADD_COMMAND                  126
#define ID_DEL_COMMAND                  127
#define IDR_MAINFRAME                   128
#define ID_COPY                         128
#define IDR_TEDITTYPE                   129
#define ID_PASTE                        129
#define ID_ADDOBJECT                    130
#define IDS_WEAPONS                     130
#define ID_CONTOURPROPS                 131
#define IDS_CLIPS                       131
#define ID_IMAGESIZE                    132
#define IDS_GRENADES                    132
#define ID_USEDXT                       133
#define ID_ASSIGN_SPOT_FRAGMENTS        133
#define IDS_FIRSTAID                    133
#define ID_AUTOSELECT_ANIM_MODEL        134
#define ID_ADDLADDER                    134
#define IDS_MINEDETECTORS               134
#define IDR_HTML_RPGITEMPREFS           135
#define ID_AUTOSELECT_ANIM_ITEMS        135
#define IDS_MELEE                       135
#define ID_ANIM_SHOWFLAGS               136
#define ID_VIEW_PROPBROWSER             136
#define ID_TOOLS_STOREITEMS             137
#define ID_TOOLS_CUSTOMIZE              200
#define IDS_COMMANDS                    201
#define IDB_PROJWSP                     202
#define IDI_TREE_ICON                   250
#define IDI_LIST_ICON                   251
#define IDR_RECTMENU                    252
#define IDD_ADD_TEMPL                   253
#define IDD_FINELEM_SELECT              254
#define IDD_OBJINSPECTOR                255
#define IDR_FOLDERS                     256
#define IDD_NEWFOLDER                   257
#define IDD_NEWITEM                     259
#define IDR_VARIANT_SEL                 264
#define IDB_NEWVARIANT                  268
#define IDB_GRIDVARIANT                 269
#define IDB_FINVARIANT                  270
#define IDB_UNITVARIANT                 271
#define IDB_DELVARIANT                  272
#define IDB_SPLASH                      273
#define IDR_WALL_MENU                   274
#define IDD_EXPORT_RESULTS              275
#define IDD_RES_LAYOUT                  276
#define IDR_TREEWND_MENU                277
#define IDR_TEMPLATE_BAR                280
#define IDC_HANDTOOL                    282
#define IDC_ZOOM                        283
#define IDD_TREE_SELECT_ITEM            284
#define IDD_ANALYSE_DATA                288
#define IDD_SCALE_COMBO                 289
#define IDR_PAINTBAR                    293
#define IDR_PALETTE                     296
#define IDD_DELETE_FOLDER               298
#define IDD_DELETE_ITEMS                300
#define IDD_LAYER                       301
#define IDD_LAYER_LIST                  304
#define IDI_DOWN                        306
#define IDI_UP                          313
#define IDI_LAYER_ADD                   314
#define IDI_LAYER_DEL                   315
#define IDD_HEIGHTS_LAYER               317
#define IDD_ADD_LAYER                   318
#define IDC_WALL                        323
#define IDC_PLUS                        325
#define IDC_RECTS                       326
#define IDC_FLOORS                      327
#define IDC_SOLIDS                      328
#define IDD_NEW_REGION                  328
#define IDD_HOLE_PROPS                  329
#define IDC_SELECTION                   330
#define IDD_TEMPLATEVIEW_PREFS          330
#define IDD_ROOM                        331
#define IDC_ERASE                       332
#define IDD_MAPBUILD_PREFS              332
#define IDB_TEMPLATE_VIEW               334
#define IDD_ADD_LIGHT                   335
#define IDB_COPYVARIANT                 337
#define IDD_EXPLOSION                   338
#define IDR_UICONTROLS_BAR              342
#define IDD_MATERIAL_EDIT               344
#define IDD_GEOMETRY_EDIT               345
#define IDD_SABPARTS_DIALOG             346
#define IDD_TEXTURESPOT_EDIT            347
#define IDD_UILAYERS                    350
#define IDD_MATERIALSET_EDIT            351
#define IDR_EDITMODE                    352
#define IDR_EDITMODE_BAR                352
#define IDR_BITMAPS                     354
#define IDD_TERRAIN_EXPORT              356
#define IDB_LINK                        360
#define IDD_WAYPOINT                    361
#define IDD_SELECT_NAME_AND_FOLDER      362
#define IDD_UNIT_ROUTE                  363
#define IDD_CAMERA_INFO                 364
#define IDD_FIND                        365
#define IDD_LISTPROP                    366
#define ID_COPYSELECTEDNAMES            367
#define ID_FILE_EXPORTACKS              368
#define IDD_FRAGMENT_DIALOG             369
#define IDD_CHAPTERSECTOR_DIALOG        370
#define IDD_WALLSPOT                    371
#define IDD_LADDER                      372
#define IDD_RPGITEM_PREFS               373
#define IDD_TEXT_EDIT                   374
#define IDD_ANIM_ITEMS                  375
#define IDD_RPGPERS_ITEMS               376
#define IDD_RPG_ALL_ITEMS               377
#define IDD_CHOOSEDATABASE              378
#define IDD_NEWSECTOR                   379
#define ID_INSERTNITEMS                 380
#define IDD_CAMERA_ANIMATION            380
#define ID_Menu                         381
#define ID_TEMPLATE_EDITSCRIPT          383
#define ID_TOOLS_SETGAMEASPECTRATIO     384
#define IDD_SUBTEMPLATE_FLAGS           385
#define IDD_GEOMETRYPIECES_EDIT         386
#define IDD_PIECE_EDIT                  387
#define IDD_DIPLOMACY_EDIT              388
#define IDD_ANIM_FLAGS                  389
#define IDD_OBJECT_BROWSER              390
#define IDD_OB_BROWSER_CONTAINER        391
#define IDD_SCRIPT_EDIT                 392
#define IDD_STORE_ITEMS                 393
#define IDD_FINDDIALOG                  394
#define IDD_FINDTEXT                    394
#define IDC_TEMPL_WIDTH                 1000
#define IDC_TEMPL_HEIGHT                1001
#define IDC_TEMPL_NAME                  1002
#define IDC_RADIO_UNIT                  1003
#define IDC_RADIO_FINELEM               1004
#define IDC_NEWFOLDERNAME               1007
#define IDC_NEWITEMNAME                 1008
#define IDC_MAYA_LOG                    1011
#define IDC_RESLAYOUT_LIST              1013
#define IDC_SELECT_ALL                  1015
#define IDC_EXPORT_HIDEWARN             1016
#define IDC_SELTREE_PLACE               1018
#define IDC_EXPORT_PREFS_SRC            1019
#define IDC_EXPORT_PREFS_DST            1020
#define IDC_EXPORT_PREFS_DB             1021
#define IDC_ANALYSEPROC_LIST            1022
#define IDC_ANALYSE                     1023
#define IDC_ANALYSE_LOG                 1024
#define IDC_REL_EMPTY                   1025
#define IDC_COMBO_SCALE                 1026
#define IDC_DELFOLDER_TEXT              1027
#define IDC_DEL_ITEMS                   1028
#define IDC_BRUSH_SELECT                1029
#define IDC_VISIBLE                     1030
#define IDC_LAYER_NAME                  1032
#define IDC_LAYER_DOWN                  1038
#define IDC_LAYER_UP                    1039
#define IDC_LAYER_ADD                   1040
#define IDC_LAYER_DEL                   1041
#define IDC_TREE_PREV_SELECTION         1042
#define IDC_MAX_HEIGHT                  1043
#define IDC_MIN_HEIGHT                  1044
#define IDC_HEIGHT_SLIDER               1045
#define IDC_CURRENT_COLOR               1046
#define IDC_LAYER_LIST                  1049
#define IDC_BRUSH_RADIUS                1050
#define IDC_HEIGHT_GROUP                1051
#define IDC_CURHEIGHT_TEXT              1052
#define IDC_AMBIENT_R                   1057
#define IDC_AMBIENT_G                   1058
#define IDC_AMBIENT_B                   1059
#define IDC_LIGHT_R                     1060
#define IDC_LIGHT_G                     1061
#define IDC_LIGHT_B                     1062
#define IDC_LIGHT_ORIGIN_X              1063
#define IDC_LIGHT_ORIGIN_Y              1064
#define IDC_LIGHT_ORIGIN_Z              1065
#define IDC_LIGHT_DIR_X                 1066
#define IDC_LIGHT_DIR_Y                 1067
#define IDC_LIGHT_DIR_Z                 1068
#define IDC_AMBIENT_COLOR               1069
#define IDC_LIGHT_COLOR                 1070
#define IDC_TERRHOLE_HEIGHT             1071
#define IDC_FOG_R                       1071
#define IDC_GLOSS_COLOR                 1071
#define IDC_TEMPLUNWINDING_DEPTH        1072
#define IDC_FOG_G                       1072
#define IDC_VAPOUR_COLOR                1072
#define IDC_TERRHOLE_RADIUS             1072
#define IDC_FOG_B                       1073
#define IDC_NEWROOM                     1074
#define IDC_FOG_COLOR                   1074
#define IDC_ROOM_LIST                   1075
#define IDC_ROOM_COLOR                  1076
#define IDC_FOLDERNAME                  1079
#define IDC_MAPBUILD_PREFS_ARGUMENTS    1080
#define IDC_EXPLPOWER                   1081
#define IDC_SELPROPMAP_PLACE            1082
#define IDC_LIGHT_LOADPRESET            1085
#define IDC_LIGHT_SAVE                  1086
#define IDC_GRASS_TYPE                  1087
#define IDC_MATERIAL_SHIFTX             1088
#define IDC_MATERIAL_SHIFTY             1089
#define IDC_MATERIAL_ROTATION           1090
#define IDC_MATERIAL_SCALE              1091
#define IDC_MATERIAL_APPEARANCE         1093
#define IDC_MATERIAL_SZAPPEARANCE       1094
#define IDC_GEOMETRY_APPEARANCE         1095
#define IDC_GEOMETRY_SZAPPEARANCE       1096
#define IDC_SUBPART_11                  1097
#define IDC_SUBPART_31                  1098
#define IDC_FOG_DISTANCE                1098
#define IDC_SUBPART_21                  1099
#define IDC_VAPOUR_HEIGHT               1099
#define IDC_SUBPART_41                  1100
#define IDC_VAPOUR_DENSITY              1100
#define IDC_SUBPART_51                  1101
#define IDC_GEOMETRY_ROTATION           1101
#define IDC_FOG_STARTDISTANCE           1101
#define IDC_UILAYER_0                   1102
#define IDC_UILAYER_1                   1103
#define IDC_MATERIAL                    1103
#define IDC_SUBPART_12                  1104
#define IDC_UILAYER_2                   1104
#define IDC_MATERIAL_SET                1104
#define IDC_SUBPART_32                  1105
#define IDC_UILAYER_3                   1105
#define IDC_MATERIAL0                   1105
#define IDC_MATERIAL_SET2               1105
#define IDC_SUBPART_22                  1106
#define IDC_UILAYER_4                   1106
#define IDC_MATERIAL1                   1106
#define IDC_CAMERA_SPEED                1106
#define IDC_MATERIAL_SET3               1106
#define IDC_SUBPART_42                  1107
#define IDC_UILAYER_5                   1107
#define IDC_MATERIAL2                   1107
#define IDC_DIRECTORY                   1107
#define IDC_MATERIAL_SET4               1107
#define IDC_SUBPART_52                  1108
#define IDC_UILAYER_6                   1108
#define IDC_MATERIAL3                   1108
#define IDC_EXPORT_ALLLAYERS            1108
#define IDC_MATERIAL_SET5               1108
#define IDC_UILAYER_7                   1109
#define IDC_SUBPART_13                  1111
#define IDC_SUBPART_33                  1112
#define IDC_LINK                        1112
#define IDC_SUBPART_23                  1113
#define IDC_SUBPART_43                  1114
#define IDC_CHECK_FLOOR_2               1114
#define IDC_SUBPART_53                  1115
#define IDC_CHECK_FLOOR_1               1115
#define IDC_CHECK_FLOOR0                1116
#define IDC_CHECK_FLOOR1                1117
#define IDC_SUBPART_14                  1118
#define IDC_CHECK_FLOOR2                1118
#define IDC_SUBPART_34                  1119
#define IDC_CHECK_FLOOR3                1119
#define IDC_SUBPART_24                  1120
#define IDC_CHECK_FLOOR4                1120
#define IDC_SUBPART_44                  1121
#define IDC_SUBPART_54                  1122
#define IDC_COMMANDS                    1122
#define IDC_SUBPART_15                  1125
#define IDC_WAYPOINTNAME                1125
#define IDC_SUBPART_35                  1126
#define IDC_TREE_PLACE                  1126
#define IDC_SUBPART_25                  1127
#define IDC_SUBPART_45                  1128
#define IDC_ROUTE                       1128
#define IDC_SUBPART_55                  1129
#define IDC_CAMERA_INFO                 1129
#define IDC_ITEM_ID                     1130
#define IDC_RADIO_ITEM_ID               1131
#define IDC_RADIO_VARIANT_ID            1132
#define IDC_VARIANT_ID                  1133
#define IDC_OPEN_OBJECT_CHECK           1134
#define IDC_GUIMODE                     1134
#define IDC_ITEMLIST                    1135
#define IDC_RADIO1                      1136
#define IDC_RADIO2                      1137
#define IDC_RADIO3                      1138
#define IDC_RADIO4                      1139
#define IDC_RADIO5                      1140
#define IDC_PROBABILITY_EDIT            1140
#define IDC_RADIO6                      1141
#define IDC_EDIT2                       1142
#define IDC_HEIGHT                      1142
#define IDC_TEMPLATESELECT              1143
#define IDC_DESCRSELECT                 1144
#define IDC_SELECTFRAGMENTS             1145
#define IDC_IMAGESELECT                 1145
#define IDC_LADDER_STEPS                1148
#define IDC_INVENTORY_CAMERA            1149
#define IDC_SLOT_CAMERA                 1150
#define IDC_AMMO_CAMERA                 1151
#define IDC_LIGHT_LIGHTMAP              1151
#define IDC_LIGHT_NORMAL                1152
#define IDC_EDIT_TEXT                   1163
#define IDC_CHECK1                      1164
#define IDC_RANDOM_SECTOR               1164
#define IDC_SHOW_PERS_ITEMS             1164
#define IDC_SHOW2DVIEW                  1164
#define IDC_UISHOWPREVIEW               1164
#define IDC_SWITCHSYSCOLORS             1164
#define IDC_OBJECTS_SHOWGROUND          1164
#define IDC_X                           1164
#define IDC_WEAPON_NoWeapon             1164
#define IDC_MATCHWHOLEWORD              1164
#define IDC_SLOT1                       1165
#define IDC_Y                           1165
#define IDC_WEAPON_Item                 1165
#define IDC_SLOT2                       1166
#define IDC_Z                           1166
#define IDC_WEAPON_Pistol               1166
#define IDC_SLOT3                       1167
#define IDC_X2                          1167
#define IDC_WEAPON_Rifle                1167
#define IDC_SLOT4                       1168
#define IDC_Y2                          1168
#define IDC_WEAPON_SubMachineGun        1168
#define IDC_SLOT5                       1169
#define IDC_Z2                          1169
#define IDC_WEAPON_MachineGun           1169
#define IDC_SLOT6                       1170
#define IDC_WEAPON_RLauncher            1170
#define IDC_SLOT7                       1171
#define IDC_WEAPON_Knife                1171
#define IDC_SLOT8                       1172
#define IDC_WEAPON_Machete              1172
#define IDC_SLOT9                       1173
#define IDC_WEAPON_Katana               1173
#define IDC_ANIM_CAP                    1174
#define IDC_WEAPON_MDetector            1174
#define IDC_ANIM_BACKPACK               1175
#define IDC_WEAPON_PKShooter            1175
#define IDC_ANIM_RIFLE                  1176
#define IDC_WEAPON_PKSlasher            1176
#define IDC_ANIM_ITEM                   1177
#define IDC_WEAPON_PKRepairer           1177
#define IDC_ANIM_SMG                    1178
#define IDC_SECTOR_ID                   1178
#define IDC_POSE_STAND                  1178
#define IDC_ANIM_MG                     1179
#define IDC_ADD_ITEM                    1179
#define IDC_SECTOR_X                    1179
#define IDC_POSE_CROUCH                 1179
#define IDC_ANIM_RL                     1180
#define IDC_ITEMS_TREE_PLACE            1180
#define IDC_SECTOR_ID3                  1180
#define IDC_SECTOR_Y                    1180
#define IDC_POSE_CRAWL                  1180
#define IDC_ANIM_HEAD                   1181
#define IDC_ITEMS_LIST                  1181
#define IDC_WEAPON_PLAZMAGUN            1181
#define IDC_WEAPON_PK_PlazmaGun         1182
#define IDC_TEST_PLACE1                 1183
#define IDC_TEST_PLACE                  1185
#define IDC_WEAPONS_PLACE               1185
#define IDC_CUSTOM1                     1186
#define IDC_CLIPS_PLACE                 1186
#define IDC_GRENADES_PLACE              1187
#define IDC_FIRSTAIDS_PLACE             1188
#define IDC_MINEDETECTORS_PLACE         1189
#define IDC_PLACE                       1190
#define IDC_DBSERVER                    1191
#define IDC_SEGMENTCOUNT                1192
#define IDC_STALPHA                     1193
#define IDC_CHECK2                      1194
#define IDC_SHOWAI_SPHERES              1194
#define IDC_MALE                        1194
#define IDC_SYNTAX_COLOURING            1194
#define IDC_SHOW_OBJ_BROWSER            1194
#define IDC_MATCHCASE                   1194
#define IDC_NUMBEROFITEMS               1195
#define IDC_INSTANTTERRAIN              1195
#define IDC_STATIC_TEMPLATE             1196
#define IDC_TERRAIN_SHOWHOLES           1196
#define IDC_COMBO1                      1197
#define IDC_GRID_INTERVAL               1197
#define IDC_ZONE                        1198
#define IDC_EXITZONE                    1199
#define IDC_KEYFRAMES                   1201
#define IDC_GENERATE_SCRIPT             1202
#define IDC_MOVING_SPEED                1203
#define IDC_GRID_SNAP                   1204
#define IDC_ERRLOG                      1205
#define IDC_LINEINFO                    1206
#define IDC_PARAMS_PLACE                1207
#define IDC_INFO_PLACE                  1208
#define IDC_PART_X                      1209
#define IDC_PART_Y                      1210
#define IDC_DIPLOMACY_PLACE             1210
#define IDC_PART_Z                      1211
#define IDC_PIECE_X                     1212
#define IDC_EDIT1                       1212
#define IDC_ORIGINAL_PIECES             1212
#define IDC_WIDTH                       1212
#define IDC_FINDTEXT                    1212
#define IDC_PIECE_Y                     1213
#define IDC_PIECE_Z                     1214
#define IDC_FEMALE                      1214
#define IDC_COMBAT                      1215
#define IDC_REALTIME                    1217
#define IDC_CLASS_Engineer              1218
#define IDC_CLASS_Grenadier             1219
#define IDC_PERS_FACEGENCAMERA          1219
#define IDC_CLASS_Medic                 1220
#define IDC_PERS_GENERALCAMERA          1220
#define IDC_CLASS_Scout                 1221
#define IDC_WND_PLACE                   1221
#define IDC_CLASS_Sniper                1222
#define IDC_CLASS_Soldier               1223
#define IDC_SCRIPT_PLACE                1223
#define IDC_CLASS_Enemy                 1224
#define IDC_STORE_LIST                  1224
#define IDC_ADD_BUTTON                  1225
#define IDC_REMOVE_BUTTON               1226
#define IDC_ALLIES                      1232
#define IDC_AXIS                        1233
#define IDC_CUSTOMFRAME                 1234
#define IDC_STATIC_W                    1235
#define IDC_STATIC_H                    1236
#define ID_FINDNEXT                     1237
#define ID_FILE_SAVEALL                 32774
#define ID_ADDRECT                      32775
#define ID_VIEW_ZOOM_50                 32776
#define ID_VIEW_ZOOM_100                32777
#define ID_VIEW_ZOOM_200                32778
#define ID_VIEW_UPDGAME                 32782
#define ID_NEWFOLDER                    32787
#define ID_DELETEFOLDER                 32788
#define ID_NEWTREEVIEW                  32789
#define ID_DELETEITEM                   32790
#define ID_NEWITEM                      32791
#define ID_NEW_VARIANT                  32792
#define ID_DELVARIANT                   32793
#define ID_DRAW_WALLS                   32795
#define ID_VIEW_PROPERTIES              32796
#define ID_DELETE_WALL                  32798
#define ID_WALL_FLIP                    32799
#define ID_EXPORTITEM                   32800
#define ID_FORCED_EXPORTITEM            32801
#define ID_EXPORT_ALL                   32803
#define ID_FORCED_EXPORTALL             32804
#define ID_RELOAD_TREE                  32805
#define ID_UPDATE_TREE                  32806
#define ID_TOOLS_RESOURCES              32807
#define ID_RESOURCETABS                 32808
#define ID_SHADOWS                      32809
#define ID_VIEW_SHADOWS                 32810
#define ID_TEMPLATE_MODE_NORMAL         32811
#define ID_TEMPLATE_MODE_ZOOM           32812
#define ID_TEMPLATE_MODE_PAN            32813
#define ID_HELP_TIPOFTHEDAY             32815
#define ID_VIEW_QUICKVIEW               32828
#define ID_FLOOR_MINUS2                 32829
#define ID_FLOOR_MINUS1                 32830
#define ID_FLOOR_0                      32831
#define ID_FLOOR_2                      32833
#define ID_FLOOR_3                      32834
#define ID_FLOOR_4                      32835
#define ID_FLOOR_1                      32836
#define ID_RENAMEITEM                   32838
#define ID_VIEW_TOOLBARS_DEFAULT        32839
#define ID_VIEW_TOOLBARS_TEMPLATETOOLS  32840
#define ID_VIEW_TOOLBARS_VARIANTSELECTION 32841
#define ID_TOOLS_ANALYSE                32842
#define ID_VIEW_PREFERENCES             32843
#define ID_GOBACK                       32847
#define ID_GOFORWARD                    32848
#define ID_TEMPLATE_SCALE               32850
#define ID_TEMPLATE_MODE_DRAWSOLIDS     32851
#define ID_VIEW_CAMERARESET             32859
#define ID_VIEW_REALTIMEPREVIEW         32863
#define ID_PAINT_PENCIL                 32867
#define ID_PAINT_PALETTE                32870
#define ID_PAINT_BRUSH                  32871
#define ID_PAINT_FILL                   32873
#define ID_PAINT_PEN3                   32875
#define ID_PAINT_PEN1                   32876
#define ID_PAINT_PEN2                   32878
#define ID_VIEW_TOOLBARS_PAINT          32879
#define ID_VIEW_GRID                    32881
#define ID_PAINT_SELECTION              32885
#define ID_PEN                          32886
#define ID_PAINT_PEN                    32887
#define ID_TEMPLATE_MODE_PAINT          32888
#define ID_MAKE_CURRENT                 32890
#define ID_VIEW_LAYERS                  32891
#define ID_FILE_EXPORTTEMPLATE          32892
#define ID_FOLDER_COLOR                 32893
#define ID_PAINT_ERASE                  32894
#define ID_VIEW_ROLL                    32895
#define ID__UPDATEDBVALUES              32897
#define ID_UPDATEDBVALUES               32898
#define ID_COPYVARIANT                  32899
#define ID_UI_TEXT                      32900
#define ID_UI_IMAGE                     32901
#define ID_UI_CHECKBUTTON               32904
#define ID_UI_MODEL                     32905
#define ID_UI_BUTTON                    32906
#define ID_UI_RADIOBUTTON               32907
#define ID_UI_SLIDER                    32908
#define ID_UI_EDIT                      32909
#define ID_UI_IMAGELIST                 32910
#define ID_UI_MESSAGEBOX                32911
#define ID_UI_CUSTOMCONTROL             32912
#define ID_UI_SELECT                    32913
#define ID_UI_GROUP                     32914
#define ID_VIEW_BUILDBRUSH              32915
#define ID_VIEW_FULLSCREEN              32916
#define ID_VIEW_WYSIWYG                 32919
#define ID_UI_WINDOW                    32920
#define ID_SELECT                       32922
#define ID_GEOMETRY                     32924
#define ID_BRUSH                        32925
#define ID_ROTATIONID                   32926
#define ID_VIEW_EDITORTOOLS             32927
#define ID_DOWNARROW                    32930
#define ID_TOOLS_CAMERA                 32932
#define ID_TOOLS_WRITERPGITEMCAMERA     32933
#define ID_FOLDER_FIND                  32934
#define ID_XY                           32936
#define ID_Z                            32938
#define ID_BUTTON32939                  32939
#define ID_UI_PUSHBUTTON                32940
#define ID_PROGRSSBAR                   32941
#define ID_UI_PROGRESSBAR               32942
#define ID_NEW_TEMPLATE_FROM_SEL        32998
#define ID_RUNGAME                      32999
#define ID_WIRESUBTEMPLATES             33000
#define ID_UI_SCROLL                    33002
#define ID_UI_COMBOBOX                  33003
#define ID_SAVE_CAMERA                  33004
#define ID_RESTORE_CAMERA               33005
#define ID_VIEW_UNIT_ROUTE              33006
#define ID_SET_UNIT_ROUTE               33007
#define ID_ANIMATE_CAMERA               33008
#define ID_LOCK_SELECTION               33009
#define ID_LOCKSELECTION                33010
#define ID_EDIT_MAPSCRIPT               33011
#define ID_TOOLS_                       33013
#define ID_PAINT_SELECTMATERIAL         33015
#define ID_VARIANT_START                35000
#define ID_VARIANT_END                  35050
#define ID_FLOOR_START                  36000
#define ID_FLOOR_END                    36050
#define IDS_ERR_EXPORT_SRC              61216
#define IDS_ERR_EXPORT_DST              61217
#define IDS_ERR_GENERIC                 61218
#define IDS_ERR_EXPORT_BAT              61219
#define IDS_ERR_EXPORT_CAPT             61220
#define IDS_EXPORT_EMPTY                61221
#define IDS_ERR_EXPORT_COPY             61222
#define IDS_ERR_DIR_PREFIX              61223
#define IDS_ERR_SET_REFRESH             61224
#define IDS_ERR_ANIMATION               61225
#define IDS_CONFIRM_DELVARIANT          61226
#define IDS_CONFIRM_DELFOLDER           61227
#define IDS_CONFIRM_DELETELAYER         61228
#define IDS_DELETE_OBJECT               61229
#define IDS_ADD_UNIT                    61230
#define IDS_ADD_TEMPLATE                61231
#define IDS_ADD_PARTICLE                61232
#define IDS_ADD_CONTAINER               61232
#define IDS_ADD_MODEL                   61233
#define IDS_ADD_LIGHT                   61234
#define IDS_NEWITEMFOLDER               61234
#define IDS_ADD_EXPLOSION               61235
#define IDS_TIP_RNDWEIGHT               61236
#define IDS_TIP_BKIMAGE                 61237
#define IDS_TIP_CONSTRUCTION_SIZEX      61238
#define IDS_TIP_CONSTRUCTION_SIZEZ      61239
#define IDS_TIP_CONSTRUCTION_THICKNESS  61240
#define IDS_WYSIWYGBAR_NAME             61241
#define IDS_TIP_CONSTRUCTION_CUTM       61242
#define IDS_TIP_CONSTRUCTION_DEFM       61243
#define IDS_TIP_CONSTRUCTION_CUTM2      61244
#define IDS_TIP_CONSTRUCTION_DEFM2      61245
#define IDS_ADD_TERRSPOT                61246

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        395
#define _APS_NEXT_COMMAND_VALUE         33016
#define _APS_NEXT_CONTROL_VALUE         1238
#define _APS_NEXT_SYMED_VALUE           138
#endif
#endif
