#ifndef __UICONTROLS_H
#define __UICONTROLS_H

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#include "dbDefs.h"
#include "..\DBFormat\DataInterface.h"
#include "PropMap.h"
////////////////////////////////////////////////////////////////////////////////////////////////////
const TCHAR UICONTROLS_TBL[] = _TEXT( "UIControls" );
////////////////////////////////////////////////////////////////////////////////////////////////////
class CUIControlAccessor
{
public:
	LONG  m_nID;
	TCHAR m_szID[MAX_DBSTRING + 1];
	LONG  m_nType;
	LONG  m_nLeft;
	LONG  m_nTop;
	LONG  m_nRight;
	LONG  m_nBottom;
	LONG  m_nTexture0;
	LONG  m_nTexture1;
	LONG  m_nTexture2;
	LONG  m_nTexture3;
	LONG  m_nTexture4;
	LONG  m_nTexture5;
	LONG  m_nModel0;
	LONG  m_nModel1;
	LONG  m_nModel2;
	LONG  m_nModel3;
	LONG  m_nModel4;
	LONG  m_nStringID;
	LONG  m_nUIContainerID;
	TCHAR m_szText[MAX_DBSTRING + 1];
	LONG  m_nNestedUIContainerID;
	LONG  m_nTooltipID;
	LONG  m_nDepth;
	LONG  m_nColor;
	LONG  m_nFreeze;
	LONG  m_bTransparent;
	LONG  m_bVisible;
	LONG  m_bTopmost;
	LONG  m_bDefaultWindow;
	LONG  m_bBottommost;
	LONG  m_nSound0;
	LONG  m_nSound1;
	LONG  m_nSound2;
	LONG  m_nSound3;
	LONG  m_nSound4;

BEGIN_ACCESSOR_MAP( CUIControlAccessor, 18 )
  BEGIN_ACCESSOR( 0, true )
		COLUMN_ENTRY(1, m_nID)
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(11, m_nTexture4)
		COLUMN_ENTRY(12, m_nModel0)
		COLUMN_ENTRY(13, m_nModel1)
		COLUMN_ENTRY(14, m_nModel2)
		COLUMN_ENTRY(15, m_nModel3)
		COLUMN_ENTRY(16, m_nModel4)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(19, m_szText)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(24, m_nColor)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(29, m_nTexture5)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
		COLUMN_ENTRY(34, m_nSound2)
		COLUMN_ENTRY(35, m_nSound3)
		COLUMN_ENTRY(36, m_nSound4)
  END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_TEXT, false )  // используется для записи в базу данных
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_IMAGE, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(24, m_nColor)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_MODEL, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(12, m_nModel0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_BUTTON, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_PUSHBUTTON, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_CHECKBUTTON, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(11, m_nTexture4)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(29, m_nTexture5)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_RADIOBUTTON, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(11, m_nTexture4)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(29, m_nTexture5)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_SCROLL, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_EDIT, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_IMAGELIST, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_MESSAGEBOX, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
	BEGIN_ACCESSOR( NDb::UI_CONTAINER, false )
		COLUMN_ENTRY(2, m_nType)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_GROUP, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
  BEGIN_ACCESSOR( NDb::UI_WINDOW, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(8, m_nTexture1)
		COLUMN_ENTRY(9, m_nTexture2)
		COLUMN_ENTRY(10, m_nTexture3)
		COLUMN_ENTRY(11, m_nTexture4)
		COLUMN_ENTRY(12, m_nModel0)
		COLUMN_ENTRY(13, m_nModel1)
		COLUMN_ENTRY(14, m_nModel2)
		COLUMN_ENTRY(15, m_nModel3)
		COLUMN_ENTRY(16, m_nModel4)
		COLUMN_ENTRY(17, m_nStringID)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(19, m_szText)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(29, m_nTexture5)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
		COLUMN_ENTRY(32, m_nSound0)
		COLUMN_ENTRY(33, m_nSound1)
		COLUMN_ENTRY(34, m_nSound2)
		COLUMN_ENTRY(35, m_nSound3)
		COLUMN_ENTRY(36, m_nSound4)
	END_ACCESSOR()
	BEGIN_ACCESSOR( NDb::UI_PROGRESSBAR, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
  END_ACCESSOR()
	BEGIN_ACCESSOR( NDb::UI_SLIDER, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
	BEGIN_ACCESSOR( NDb::UI_COMBOBOX, false )
		COLUMN_ENTRY(2, m_nType)
		COLUMN_ENTRY(3, m_nLeft)
		COLUMN_ENTRY(4, m_nTop)
		COLUMN_ENTRY(5, m_nRight)
		COLUMN_ENTRY(6, m_nBottom)
		COLUMN_ENTRY(7, m_nTexture0)
		COLUMN_ENTRY(18, m_nUIContainerID)
		COLUMN_ENTRY(20, m_szID)
		COLUMN_ENTRY(21, m_nNestedUIContainerID)
		COLUMN_ENTRY(22, m_nTooltipID)
		COLUMN_ENTRY(23, m_nDepth)
		COLUMN_ENTRY(25, m_nFreeze)
		COLUMN_ENTRY(26, m_bTransparent)
		COLUMN_ENTRY(27, m_bVisible)
		COLUMN_ENTRY(28, m_bTopmost)
		COLUMN_ENTRY(30, m_bDefaultWindow)
		COLUMN_ENTRY(31, m_bBottommost)
	END_ACCESSOR()
	END_ACCESSOR_MAP()

	void ClearRecord() { memset(this, 0, sizeof(*this)); }
	void CopyAccessor( const CUIControlAccessor *pA ) { *this = *pA; }
};
////////////////////////////////////////////////////////////////////////////////////////////////////
class CUIControl: public CBaseDBCmd<CAccessor<CUIControlAccessor> >, public CObjectBase
{
	OBJECT_BASIC_METHODS(CUIControl);

	CRect rect;
	CPropMap	props;
	int nID;
	int nUIContainerID;

	void AddProp( const string &szName, int nType, int nViewType, const CVariant &val, void *pValue, bool bReadOnly = false, int nGroup = CProp::PROPDEF_GROUP );
	void SetStrType( int nStringID );
	void SetRelation( const string &szName, int nResTreeID );
	void SetPrefix( const string &szName, const string &szPrefix );
	void SetTip( const string &szName, int nResStrID );

public:
	CUIControl() { ClearRecord(); }

	void Setup( int nUIContainerID );									// создание props по значениям в CUIControlAccessor
	bool Open();
	virtual HRESULT Open( const std::string &szQuery ) { return CBaseDBCmd<CAccessor<CUIControlAccessor> >::Open( szQuery ); }

	const CPropMap* GetPropMap() const;
	bool Update( bool bSaveData = true );
	bool SetRect( CRect rect, bool bSaveData = true );
	void CheckRect();

	int GetID() const { return nID; }
	void SetID( int nNewID ) { nID = nNewID; }
	const CRect& GetRect() const { return rect; }
	bool IsFreeze() const { return m_nFreeze; }
	bool SyncWithImageSize();
};
////////////////////////////////////////////////////////////////////////////////////////////////////
#endif // __UICONTROLS_H